### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by jiujing23333** [vt-vl-lab/tf_flownet2#6]
When I try to import the correlation kernel, it report error:
`Traceback (most recent call last):
  File "/home/user/work/tf_flownet2/FlowNet2_src/test.py", line 6, in <module>
    tf.resource_loader.get_path_to_datafile("./ops/build/correlation.so"))
  File "/home/earhian/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/work/tf_flownet2/FlowNet2_src/./ops/build/correlation.so: undefined symbol: _ZTIN10tensorflow8OpKernelE`

**Comment by Yuliang-Zou** [comment]
What's your TF version? We used 1.2.0 here.
